<?php

/**
 * Base class that represents a row from the 'USUARIO' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/05/09 19:06:57
 *
 * @package    lib.model.om
 */
abstract class BaseUsuario extends BaseObject  implements Persistent {


  const PEER = 'UsuarioPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UsuarioPeer
	 */
	protected static $peer;

	/**
	 * The value for the nick field.
	 * @var        string
	 */
	protected $nick;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the apellido field.
	 * @var        string
	 */
	protected $apellido;

	/**
	 * The value for the correo field.
	 * @var        string
	 */
	protected $correo;

	/**
	 * The value for the credito field.
	 * @var        double
	 */
	protected $credito;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the estado field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $estado;

	/**
	 * The value for the fklugar field.
	 * @var        int
	 */
	protected $fklugar;

	/**
	 * @var        Lugar
	 */
	protected $aLugar;

	/**
	 * @var        array Telefono[] Collection to store aggregation of Telefono objects.
	 */
	protected $collTelefonos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTelefonos.
	 */
	private $lastTelefonoCriteria = null;

	/**
	 * @var        array Usuarioformapago[] Collection to store aggregation of Usuarioformapago objects.
	 */
	protected $collUsuarioformapagos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsuarioformapagos.
	 */
	private $lastUsuarioformapagoCriteria = null;

	/**
	 * @var        array Apuesta[] Collection to store aggregation of Apuesta objects.
	 */
	protected $collApuestas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collApuestas.
	 */
	private $lastApuestaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUsuario object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->estado = false;
	}

	/**
	 * Get the [nick] column value.
	 * 
	 * @return     string
	 */
	public function getNick()
	{
		return $this->nick;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [apellido] column value.
	 * 
	 * @return     string
	 */
	public function getApellido()
	{
		return $this->apellido;
	}

	/**
	 * Get the [correo] column value.
	 * 
	 * @return     string
	 */
	public function getCorreo()
	{
		return $this->correo;
	}

	/**
	 * Get the [credito] column value.
	 * 
	 * @return     double
	 */
	public function getCredito()
	{
		return $this->credito;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [estado] column value.
	 * 
	 * @return     boolean
	 */
	public function getEstado()
	{
		return $this->estado;
	}

	/**
	 * Get the [fklugar] column value.
	 * 
	 * @return     int
	 */
	public function getFklugar()
	{
		return $this->fklugar;
	}

	/**
	 * Set the value of [nick] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setNick($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nick !== $v) {
			$this->nick = $v;
			$this->modifiedColumns[] = UsuarioPeer::NICK;
		}

		return $this;
	} // setNick()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = UsuarioPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [apellido] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setApellido($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->apellido !== $v) {
			$this->apellido = $v;
			$this->modifiedColumns[] = UsuarioPeer::APELLIDO;
		}

		return $this;
	} // setApellido()

	/**
	 * Set the value of [correo] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setCorreo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->correo !== $v) {
			$this->correo = $v;
			$this->modifiedColumns[] = UsuarioPeer::CORREO;
		}

		return $this;
	} // setCorreo()

	/**
	 * Set the value of [credito] column.
	 * 
	 * @param      double $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setCredito($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->credito !== $v) {
			$this->credito = $v;
			$this->modifiedColumns[] = UsuarioPeer::CREDITO;
		}

		return $this;
	} // setCredito()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = UsuarioPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [estado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setEstado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->estado !== $v || $v === false) {
			$this->estado = $v;
			$this->modifiedColumns[] = UsuarioPeer::ESTADO;
		}

		return $this;
	} // setEstado()

	/**
	 * Set the value of [fklugar] column.
	 * 
	 * @param      int $v new value
	 * @return     Usuario The current object (for fluent API support)
	 */
	public function setFklugar($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fklugar !== $v) {
			$this->fklugar = $v;
			$this->modifiedColumns[] = UsuarioPeer::FKLUGAR;
		}

		if ($this->aLugar !== null && $this->aLugar->getId() !== $v) {
			$this->aLugar = null;
		}

		return $this;
	} // setFklugar()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(UsuarioPeer::ESTADO))) {
				return false;
			}

			if ($this->estado !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->nick = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->apellido = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->correo = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->credito = ($row[$startcol + 4] !== null) ? (double) $row[$startcol + 4] : null;
			$this->password = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->estado = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->fklugar = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = UsuarioPeer::NUM_COLUMNS - UsuarioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Usuario object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aLugar !== null && $this->fklugar !== $this->aLugar->getId()) {
			$this->aLugar = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UsuarioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aLugar = null;
			$this->collTelefonos = null;
			$this->lastTelefonoCriteria = null;

			$this->collUsuarioformapagos = null;
			$this->lastUsuarioformapagoCriteria = null;

			$this->collApuestas = null;
			$this->lastApuestaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUsuario:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UsuarioPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUsuario:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUsuario:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUsuario:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UsuarioPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aLugar !== null) {
				if ($this->aLugar->isModified() || $this->aLugar->isNew()) {
					$affectedRows += $this->aLugar->save($con);
				}
				$this->setLugar($this->aLugar);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UsuarioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += UsuarioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTelefonos !== null) {
				foreach ($this->collTelefonos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUsuarioformapagos !== null) {
				foreach ($this->collUsuarioformapagos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collApuestas !== null) {
				foreach ($this->collApuestas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aLugar !== null) {
				if (!$this->aLugar->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aLugar->getValidationFailures());
				}
			}


			if (($retval = UsuarioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTelefonos !== null) {
					foreach ($this->collTelefonos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUsuarioformapagos !== null) {
					foreach ($this->collUsuarioformapagos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collApuestas !== null) {
					foreach ($this->collApuestas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getNick();
				break;
			case 1:
				return $this->getNombre();
				break;
			case 2:
				return $this->getApellido();
				break;
			case 3:
				return $this->getCorreo();
				break;
			case 4:
				return $this->getCredito();
				break;
			case 5:
				return $this->getPassword();
				break;
			case 6:
				return $this->getEstado();
				break;
			case 7:
				return $this->getFklugar();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UsuarioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getNick(),
			$keys[1] => $this->getNombre(),
			$keys[2] => $this->getApellido(),
			$keys[3] => $this->getCorreo(),
			$keys[4] => $this->getCredito(),
			$keys[5] => $this->getPassword(),
			$keys[6] => $this->getEstado(),
			$keys[7] => $this->getFklugar(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setNick($value);
				break;
			case 1:
				$this->setNombre($value);
				break;
			case 2:
				$this->setApellido($value);
				break;
			case 3:
				$this->setCorreo($value);
				break;
			case 4:
				$this->setCredito($value);
				break;
			case 5:
				$this->setPassword($value);
				break;
			case 6:
				$this->setEstado($value);
				break;
			case 7:
				$this->setFklugar($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UsuarioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setNick($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setApellido($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCorreo($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCredito($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setPassword($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setEstado($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFklugar($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);

		if ($this->isColumnModified(UsuarioPeer::NICK)) $criteria->add(UsuarioPeer::NICK, $this->nick);
		if ($this->isColumnModified(UsuarioPeer::NOMBRE)) $criteria->add(UsuarioPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(UsuarioPeer::APELLIDO)) $criteria->add(UsuarioPeer::APELLIDO, $this->apellido);
		if ($this->isColumnModified(UsuarioPeer::CORREO)) $criteria->add(UsuarioPeer::CORREO, $this->correo);
		if ($this->isColumnModified(UsuarioPeer::CREDITO)) $criteria->add(UsuarioPeer::CREDITO, $this->credito);
		if ($this->isColumnModified(UsuarioPeer::PASSWORD)) $criteria->add(UsuarioPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(UsuarioPeer::ESTADO)) $criteria->add(UsuarioPeer::ESTADO, $this->estado);
		if ($this->isColumnModified(UsuarioPeer::FKLUGAR)) $criteria->add(UsuarioPeer::FKLUGAR, $this->fklugar);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);

		$criteria->add(UsuarioPeer::NICK, $this->nick);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getNick();
	}

	/**
	 * Generic method to set the primary key (nick column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setNick($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Usuario (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNick($this->nick);

		$copyObj->setNombre($this->nombre);

		$copyObj->setApellido($this->apellido);

		$copyObj->setCorreo($this->correo);

		$copyObj->setCredito($this->credito);

		$copyObj->setPassword($this->password);

		$copyObj->setEstado($this->estado);

		$copyObj->setFklugar($this->fklugar);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTelefonos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTelefono($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUsuarioformapagos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUsuarioformapago($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getApuestas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addApuesta($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Usuario Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UsuarioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UsuarioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Lugar object.
	 *
	 * @param      Lugar $v
	 * @return     Usuario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setLugar(Lugar $v = null)
	{
		if ($v === null) {
			$this->setFklugar(NULL);
		} else {
			$this->setFklugar($v->getId());
		}

		$this->aLugar = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Lugar object, it will not be re-added.
		if ($v !== null) {
			$v->addUsuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated Lugar object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Lugar The associated Lugar object.
	 * @throws     PropelException
	 */
	public function getLugar(PropelPDO $con = null)
	{
		if ($this->aLugar === null && ($this->fklugar !== null)) {
			$c = new Criteria(LugarPeer::DATABASE_NAME);
			$c->add(LugarPeer::ID, $this->fklugar);
			$this->aLugar = LugarPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aLugar->addUsuarios($this);
			 */
		}
		return $this->aLugar;
	}

	/**
	 * Clears out the collTelefonos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTelefonos()
	 */
	public function clearTelefonos()
	{
		$this->collTelefonos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTelefonos collection (array).
	 *
	 * By default this just sets the collTelefonos collection to an empty array (like clearcollTelefonos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTelefonos()
	{
		$this->collTelefonos = array();
	}

	/**
	 * Gets an array of Telefono objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usuario has previously been saved, it will retrieve
	 * related Telefonos from storage. If this Usuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Telefono[]
	 * @throws     PropelException
	 */
	public function getTelefonos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTelefonos === null) {
			if ($this->isNew()) {
			   $this->collTelefonos = array();
			} else {

				$criteria->add(TelefonoPeer::FKUSUARIO, $this->nick);

				TelefonoPeer::addSelectColumns($criteria);
				$this->collTelefonos = TelefonoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TelefonoPeer::FKUSUARIO, $this->nick);

				TelefonoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTelefonoCriteria) || !$this->lastTelefonoCriteria->equals($criteria)) {
					$this->collTelefonos = TelefonoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTelefonoCriteria = $criteria;
		return $this->collTelefonos;
	}

	/**
	 * Returns the number of related Telefono objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Telefono objects.
	 * @throws     PropelException
	 */
	public function countTelefonos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTelefonos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TelefonoPeer::FKUSUARIO, $this->nick);

				$count = TelefonoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TelefonoPeer::FKUSUARIO, $this->nick);

				if (!isset($this->lastTelefonoCriteria) || !$this->lastTelefonoCriteria->equals($criteria)) {
					$count = TelefonoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTelefonos);
				}
			} else {
				$count = count($this->collTelefonos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Telefono object to this object
	 * through the Telefono foreign key attribute.
	 *
	 * @param      Telefono $l Telefono
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTelefono(Telefono $l)
	{
		if ($this->collTelefonos === null) {
			$this->initTelefonos();
		}
		if (!in_array($l, $this->collTelefonos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTelefonos, $l);
			$l->setUsuario($this);
		}
	}

	/**
	 * Clears out the collUsuarioformapagos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsuarioformapagos()
	 */
	public function clearUsuarioformapagos()
	{
		$this->collUsuarioformapagos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsuarioformapagos collection (array).
	 *
	 * By default this just sets the collUsuarioformapagos collection to an empty array (like clearcollUsuarioformapagos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsuarioformapagos()
	{
		$this->collUsuarioformapagos = array();
	}

	/**
	 * Gets an array of Usuarioformapago objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usuario has previously been saved, it will retrieve
	 * related Usuarioformapagos from storage. If this Usuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Usuarioformapago[]
	 * @throws     PropelException
	 */
	public function getUsuarioformapagos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsuarioformapagos === null) {
			if ($this->isNew()) {
			   $this->collUsuarioformapagos = array();
			} else {

				$criteria->add(UsuarioformapagoPeer::FKUSUARIO, $this->nick);

				UsuarioformapagoPeer::addSelectColumns($criteria);
				$this->collUsuarioformapagos = UsuarioformapagoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UsuarioformapagoPeer::FKUSUARIO, $this->nick);

				UsuarioformapagoPeer::addSelectColumns($criteria);
				if (!isset($this->lastUsuarioformapagoCriteria) || !$this->lastUsuarioformapagoCriteria->equals($criteria)) {
					$this->collUsuarioformapagos = UsuarioformapagoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUsuarioformapagoCriteria = $criteria;
		return $this->collUsuarioformapagos;
	}

	/**
	 * Returns the number of related Usuarioformapago objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Usuarioformapago objects.
	 * @throws     PropelException
	 */
	public function countUsuarioformapagos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsuarioformapagos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UsuarioformapagoPeer::FKUSUARIO, $this->nick);

				$count = UsuarioformapagoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UsuarioformapagoPeer::FKUSUARIO, $this->nick);

				if (!isset($this->lastUsuarioformapagoCriteria) || !$this->lastUsuarioformapagoCriteria->equals($criteria)) {
					$count = UsuarioformapagoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUsuarioformapagos);
				}
			} else {
				$count = count($this->collUsuarioformapagos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Usuarioformapago object to this object
	 * through the Usuarioformapago foreign key attribute.
	 *
	 * @param      Usuarioformapago $l Usuarioformapago
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUsuarioformapago(Usuarioformapago $l)
	{
		if ($this->collUsuarioformapagos === null) {
			$this->initUsuarioformapagos();
		}
		if (!in_array($l, $this->collUsuarioformapagos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsuarioformapagos, $l);
			$l->setUsuario($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usuario is new, it will return
	 * an empty collection; or if this Usuario has previously
	 * been saved, it will retrieve related Usuarioformapagos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usuario.
	 */
	public function getUsuarioformapagosJoinFormapago($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsuarioformapagos === null) {
			if ($this->isNew()) {
				$this->collUsuarioformapagos = array();
			} else {

				$criteria->add(UsuarioformapagoPeer::FKUSUARIO, $this->nick);

				$this->collUsuarioformapagos = UsuarioformapagoPeer::doSelectJoinFormapago($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UsuarioformapagoPeer::FKUSUARIO, $this->nick);

			if (!isset($this->lastUsuarioformapagoCriteria) || !$this->lastUsuarioformapagoCriteria->equals($criteria)) {
				$this->collUsuarioformapagos = UsuarioformapagoPeer::doSelectJoinFormapago($criteria, $con, $join_behavior);
			}
		}
		$this->lastUsuarioformapagoCriteria = $criteria;

		return $this->collUsuarioformapagos;
	}

	/**
	 * Clears out the collApuestas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addApuestas()
	 */
	public function clearApuestas()
	{
		$this->collApuestas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collApuestas collection (array).
	 *
	 * By default this just sets the collApuestas collection to an empty array (like clearcollApuestas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initApuestas()
	{
		$this->collApuestas = array();
	}

	/**
	 * Gets an array of Apuesta objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Usuario has previously been saved, it will retrieve
	 * related Apuestas from storage. If this Usuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Apuesta[]
	 * @throws     PropelException
	 */
	public function getApuestas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collApuestas === null) {
			if ($this->isNew()) {
			   $this->collApuestas = array();
			} else {

				$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

				ApuestaPeer::addSelectColumns($criteria);
				$this->collApuestas = ApuestaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

				ApuestaPeer::addSelectColumns($criteria);
				if (!isset($this->lastApuestaCriteria) || !$this->lastApuestaCriteria->equals($criteria)) {
					$this->collApuestas = ApuestaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastApuestaCriteria = $criteria;
		return $this->collApuestas;
	}

	/**
	 * Returns the number of related Apuesta objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Apuesta objects.
	 * @throws     PropelException
	 */
	public function countApuestas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collApuestas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

				$count = ApuestaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

				if (!isset($this->lastApuestaCriteria) || !$this->lastApuestaCriteria->equals($criteria)) {
					$count = ApuestaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collApuestas);
				}
			} else {
				$count = count($this->collApuestas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Apuesta object to this object
	 * through the Apuesta foreign key attribute.
	 *
	 * @param      Apuesta $l Apuesta
	 * @return     void
	 * @throws     PropelException
	 */
	public function addApuesta(Apuesta $l)
	{
		if ($this->collApuestas === null) {
			$this->initApuestas();
		}
		if (!in_array($l, $this->collApuestas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collApuestas, $l);
			$l->setUsuario($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usuario is new, it will return
	 * an empty collection; or if this Usuario has previously
	 * been saved, it will retrieve related Apuestas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usuario.
	 */
	public function getApuestasJoinEvento($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collApuestas === null) {
			if ($this->isNew()) {
				$this->collApuestas = array();
			} else {

				$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

				$this->collApuestas = ApuestaPeer::doSelectJoinEvento($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

			if (!isset($this->lastApuestaCriteria) || !$this->lastApuestaCriteria->equals($criteria)) {
				$this->collApuestas = ApuestaPeer::doSelectJoinEvento($criteria, $con, $join_behavior);
			}
		}
		$this->lastApuestaCriteria = $criteria;

		return $this->collApuestas;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Usuario is new, it will return
	 * an empty collection; or if this Usuario has previously
	 * been saved, it will retrieve related Apuestas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Usuario.
	 */
	public function getApuestasJoinEquipo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collApuestas === null) {
			if ($this->isNew()) {
				$this->collApuestas = array();
			} else {

				$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

				$this->collApuestas = ApuestaPeer::doSelectJoinEquipo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ApuestaPeer::FKUSUARIO, $this->nick);

			if (!isset($this->lastApuestaCriteria) || !$this->lastApuestaCriteria->equals($criteria)) {
				$this->collApuestas = ApuestaPeer::doSelectJoinEquipo($criteria, $con, $join_behavior);
			}
		}
		$this->lastApuestaCriteria = $criteria;

		return $this->collApuestas;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTelefonos) {
				foreach ((array) $this->collTelefonos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUsuarioformapagos) {
				foreach ((array) $this->collUsuarioformapagos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collApuestas) {
				foreach ((array) $this->collApuestas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTelefonos = null;
		$this->collUsuarioformapagos = null;
		$this->collApuestas = null;
			$this->aLugar = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUsuario:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUsuario::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUsuario
